YOUTRUSTの本番に合わせる

diff --git a/.github/workflows/git-pr-release.yml b/.github/workflows/git-pr-release.yml
--- a/.github/workflows/git-pr-release.yml
+++ b/.github/workflows/git-pr-release.yml
@@ -7,7 +7,7 @@ jobs:
   git-pr-release:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - name: Set up Ruby 3.1
@@ -18,10 +18,33 @@ jobs:
         id: vars
         run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
       - run: gem install --no-document git-pr-release
-      - run: git-pr-release
+      - name: Run git-pr-release and capture output
+        id: gitpr
+        run: |
+          git-pr-release 2>&1 | tee output.txt
+          echo "::set-output name=exit_code::$?"
+        continue-on-error: true
         env:
           GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GIT_PR_RELEASE_BRANCH_PRODUCTION: main # YOUTRUSTとは異なる
+          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
           GIT_PR_RELEASE_BRANCH_STAGING: ${{ steps.vars.outputs.branch_name }}
           GIT_PR_RELEASE_LABELS: リリース用
           GIT_PR_RELEASE_TEMPLATE: .github/RELEASE_PULL_REQUEST_TEMPLATE.erb
+      - name: Check for specific error message
+        id: check
+        run: |
+          if [[ "${{ steps.gitpr.outputs.exit_code }}" == "0" ]]; then
+            echo "git-pr-release succeeded, setting job status to succeed."
+            echo "::set-output name=status::succeed"
+          elif grep -q "No pull requests to be released" output.txt; then
+            echo "Found the specific error, setting job status to succeed."
+            echo "::set-output name=status::succeed"
+          else
+            echo "Did not find the specific error or success, setting job status to fail."
+            echo "::set-output name=status::fail"
+          fi
+      - name: Conditionally fail the job
+        run: |
+          if [[ "${{ steps.check.outputs.status }}" == "fail" ]]; then
+            exit 1
+          fi
